# Generated by Django 3.0.7 on 2020-07-07 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='firendly_name',
            new_name='friendly_name',
        ),
    ]
